//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcroniManager.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class AcroniManagerDatabaseModelContainer : DbContext
    {
        public AcroniManagerDatabaseModelContainer()
            : base("name=AcroniManagerDatabaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acronym> AcronymSet { get; set; }
        public virtual DbSet<Meaning> MeaningSet { get; set; }
        public virtual DbSet<Category> CategorySet { get; set; }
        public virtual DbSet<Execution> ExecutionSet { get; set; }
        public virtual DbSet<Resource> ResourceSet { get; set; }
        public virtual DbSet<Crawler> CrawlerSet { get; set; }
        public virtual DbSet<Matcher> MatcherSet { get; set; }
        public virtual DbSet<Parameter> ParameterSet { get; set; }
        public virtual DbSet<Configuration> ConfigurationSet { get; set; }
        public virtual DbSet<Source> SourceSet { get; set; }
        public virtual DbSet<Validator> ValidatorSet { get; set; }
        public virtual DbSet<Validation> ValidationSet { get; set; }
        public virtual DbSet<Arrangement> ArrangementSet { get; set; }
    }
}
